# Generated by Django 5.0 on 2024-09-25 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('museum_id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='museums/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('closing_days', models.CharField(blank=True, help_text="Comma-separated days when the museum is closed, e.g., 'Monday, Tuesday'.", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Museum',
                'verbose_name_plural': 'Museums',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(help_text="Start time for the slot, e.g., '09:00 AM'")),
                ('end_time', models.TimeField(help_text="End time for the slot, e.g., '11:00 AM'")),
                ('tickets_available', models.PositiveIntegerField(default=0)),
                ('is_closed', models.BooleanField(default=False)),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='app2.museum')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'ordering': ['museum', 'day', 'start_time'],
                'unique_together': {('museum', 'day', 'start_time', 'end_time')},
            },
        ),
    ]
