# Generated by Django 5.0 on 2024-09-25 09:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_alter_museum_closing_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumOwnerLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='museum',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
