# Generated by Django 5.0 on 2024-09-25 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_museumownerlogin_alter_museum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app2.museumownerlogin'),
        ),
    ]
