# Generated by Django 5.0 on 2024-09-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_museum_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museum',
            name='owner',
        ),
        migrations.AddField(
            model_name='museum',
            name='owner_login',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='museum', to='app2.museumownerlogin'),
        ),
    ]
