# Generated by Django 5.0 on 2024-09-25 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_museumownerlogin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='museumownerlogin',
            name='user',
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app2.museumownerlogin')),
            ],
        ),
    ]
