# Generated by Django 5.0 on 2024-09-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_museum_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='fare',
            field=models.IntegerField(default=0),
        ),
    ]
