# Generated by Django 5.0 on 2024-09-28 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_alter_museum_fare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['museum', 'day'], 'verbose_name': 'Availability', 'verbose_name_plural': 'Availabilities'},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('museum', 'day', 'date')},
        ),
        migrations.AddField(
            model_name='availability',
            name='closing_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text="Closing time of the museum, e.g., '06:00 PM'"),
        ),
        migrations.AddField(
            model_name='availability',
            name='opening_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_time',
        ),
    ]
