# Generated by Django 5.0 on 2024-09-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='shift',
            field=models.CharField(default='Morning', max_length=20),
        ),
    ]
